### ISSUE TITLE
New Features

### ISSUE THREAD

**Issue by r17x** [r17x/fetch.macro#22]
# New Features

> Hacktoberfest has arrived

At this project we want to deliver new feature, the new feature is based on  *fetch specification at whatwag* - [See here](https://fetch.spec.whatwg.org/#body-mixin)

![image](https://user-images.githubusercontent.com/16365952/193467166-a51679c2-d35c-4c36-936a-8e7312de2d0f.png)

## Example Usage

```javascript
import { fetchText, fetchJson, fetchBlob, fetchArrayBuffer, fetchFormData } from 'fetch.macro'

const fetchSomeText = fetchText`/api/v1/user/:id/project/:projectId/:others`;

const fetchSomeJson = fetchJson`/api/v1/user/:id/project/:projectId/:others`;

const fetchSomeBlob = fetchBlob`/api/v1/user/:id/project/:projectId/:others`;

const fetchSomeArrayBuffer = fetchArrayBuffer`/api/v1/user/:id/project/:projectId/:others`;

const fetchSomeFormData = fetchFormData`/api/v1/user/:id/project/:projectId/:others`;
```

## Todo
This is lists for new API at `fetch.macro` modules.

Before start the contrbution, we have been provide code flag for make our easy to write code implementation or test case. 
 
 This the line of code related with this issue and step to contributed:

1. Write Reference name - reference  name is import module name (e.g: `fetchText`) - [See Here](https://github.com/r17x/fetch.macro/blob/main/src/fetch.macro.js#L32-L38)
2. Write Member Expression implementation - (e.g: `.then(r => r.json)`) - [See Here](https://github.com/r17x/fetch.macro/blob/main/src/fetch.macro.js#L17-L23)
3. Apply transformation - [See here](https://github.com/r17x/fetch.macro/blob/main/src/fetch.macro.js#L89-L95)
4. ~~Write little documentation at README.md - [Example: fetchText](https://github.com/r17x/fetch.macro#fetchtext)~~ (Skip this step, go to step `5.`, write documentation about api in test case)
5. Write Test Case in fetch.test.js - [See here](https://github.com/r17x/fetch.macro/blob/main/tests/test-cases.js#L105-L119)

- [x] fetchText - #23 
- [x] fetchJson - #24
- [x] fetchBlob - #28 
- [x] fetchArrayBuffer #34 
- [x] fetchFormData  - #31 
- [x] fetchClone - Basically just `Response.clone` - This is low priority but no problem to include as the new features - @fzn0x  - Thanks to @afrianjunior 

Thanks for you contribution and happy hacking

**Comment by r17x** [comment]
If you have some idea, feel free for put your approach here!

Thanks

**Comment by fzn0x** [comment]
There is also one more feature called `Request.clone` [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Request/clone) Maybe it's nice to have it here :))

**Comment by r17x** [comment]
Thanks good for me but we need to make the constructor `Request` before make a part of it. Could you elaborate more about `Request.clone` idea? 
 @fzn0x

**Comment by fzn0x** [comment]
> Thanks good for me but we need to make the constructor `Request` before make a part of it. Could you elaborate more about `Request.clone` idea? @fzn0x
> 
> Hm did you mean `Response.clone` ? @fzn0x
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Response/clone
> 
> If you want to take this, just go to open PRs 😊

Yup `Response.clone` sorry for the typo haha, uhh sweet if I find a good time I will try to open a PR :D

**Comment by r17x** [comment]
@fzn0x  I have been updated this issue. Nope, I think `Response.clone` is low priority and you can take this for new feature. 

Anyway take your time!
