### ISSUE TITLE
setup: using @swc/jest

### ISSUE THREAD

**Issue by r17x** [r17x/fetch.macro#55]
**Is your feature request related to a problem? Please describe.**
This is not feature, this is just want to use `@swc/jest`

**Describe the solution you'd like**
Since, want to provided `fetch.macro` in `swc` as swc-plugin. It's better to integrated with [@swc/jest](https://swc.rs/docs/usage/jest).

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by vadhe** [comment]
I have been PR for integrate to swc/jest but there is a error pipeline 
https://github.com/r17x/fetch.macro/pull/82
